services:
  frontend:
    build: ./StackG2-VUE-Front
    ports:
      - "5173:5173"
    networks:
      - g2net
    volumes:
      - ./StackG2-VUE-Front:/app
      - /app/node_modules  # Evita conflictos con node_modules del host
    environment:
      - CHOKIDAR_USEPOLLING=true  # Permite hot reload en Docker para Vite

  apigateway:
    build: ./ApiGateway-G2
    ports:
      - "4000:4000"
    networks:
      - g2net

networks:
  g2net:
    driver: bridge
